"use client";
import {
	Box,
	Card,
	Inset,
	Heading,
	Text,
	Flex,
	Separator,
	Badge,
} from "@radix-ui/themes";
import Link from "next/link";
import React from "react";

interface Props {
	article: Article;
	className?: string;
}

const ArticleCard = ({ article, className }: Props) => {
	console.log(article);
	return (
		<Link href={`articles/${article.id}`} className={className}>
			<Box width="calc(100vw - 42px)" maxWidth="350px" pb="6">
				<Card className="shadow-lg">
					<Inset clip="padding-box" side="top" pb="current">
						<div className="absolute p-3 top-[90px] w-[100%]">
							<Heading color="sky">{article.title}</Heading>
						</div>
						<img
							src={`data:image/jpeg;base64, ${article.cover}`}
							style={{
								display: "block",
								objectFit: "cover",
								width: "100%",
								height: 250,
								opacity: 0.2,
							}}
						/>
					</Inset>
					<Flex py="1">
						<Text size="2">
							{article.description.length > 110
								? article.description.substring(0, 110) + " [...]"
								: article.description}
						</Text>
					</Flex>
					<Flex direction="column" gap="3" mb="3">
						{article.internalUseOnly && (
							<Flex direction="column">
								<Separator my="3" size="4" />
								<Flex>
									<Badge color="orange" mr="2">
										!
									</Badge>
									<Text size="2">This article is for internal use only</Text>
								</Flex>
							</Flex>
						)}
						{article.aiGenerated && (
							<Flex direction="column">
								<Flex>
									<Badge color="green" mr="2">
										AI
									</Badge>
									<Text size="2">This article was generated by AI</Text>
								</Flex>
							</Flex>
						)}
					</Flex>
				</Card>
			</Box>
		</Link>
	);
};

export default ArticleCard;
