import { Container, Grid, Flex, Box, Heading, Text, Badge, AspectRatio, Skeleton, Separator, Card } from '@radix-ui/themes'
import React from 'react'

const Loading = () => {
  return (
    <Container>
        <Flex justify="end" mb="3">
            <Skeleton width={"300px"} height={"30px"} mt="4" mb="1"></Skeleton>
			</Flex>
				<AspectRatio ratio={6 / 3}>
					<Skeleton height={"100%"}></Skeleton>
				</AspectRatio>
			<Grid columns={{ initial: "1", md: "3" }} mt="5">
				<Box className="col-span-2" mr="3">
					<Flex mb="5" direction="column" gap="3">
						<Flex
							justify="between"
							direction={{ initial: "column", md: "row" }}
							gap={{ initial: "3", md: "0" }}
						>
							<Skeleton height={"30px"} width={"100%"}></Skeleton>
						</Flex>
						<Skeleton width={"100%"} height={"100px"}></Skeleton>
					</Flex>
					<Flex gap="3" direction="column">
							<Flex direction="column">
								<Separator my="3" size="4" />
								<Flex>
									<Badge color="orange" mr="2">
										Warning
									</Badge>
									<Text>This article is for internal use only</Text>
								</Flex>
							</Flex>
							<Flex direction="column">
								<Flex>
									<Badge color="green" mr="2">
										AI
									</Badge>
									<Text>This article was generated by AI</Text>
								</Flex>
							</Flex>
					</Flex>
				</Box>
				<Box>
					<Card className="shadow-lg">
						<Box p="3">
							<Heading size="2">Duration</Heading>
							<Text><Skeleton></Skeleton></Text>

							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Media</Heading>
								<Text><Skeleton></Skeleton></Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Source</Heading>
								<Text><Skeleton></Skeleton></Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Educational Framework</Heading>
								<Text><Skeleton></Skeleton></Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Educational Methodology</Heading>
								<Text><Skeleton></Skeleton></Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Educational Tool</Heading>
								<Text><Skeleton></Skeleton></Text>
							</Flex>

							<Separator my="3" size="4" />
							<Flex>
							</Flex>
						</Box>
					</Card>
				</Box>
			</Grid>
    </Container>
  )
}

export default Loading