import {
	Flex,
	Container,
	Grid,
	Box,
	Card,
	Heading,
	Text,
	Separator,
	Badge,
	Button,
	AspectRatio,
} from "@radix-ui/themes";
import React, { Suspense } from "react";
import Link from "next/link";
import { isAuthorized } from "@/app/utils/roleRules";
import fetchInterceptor from "@/app/utils/fetchInterceptor";
import DownloadFile from "../_components/DownloadFile";
import PinArticleButton from "../_components/PinArticleButton";
import ArticleRelevanceForJobTitleSkills from "../_components/ArticleRelevanceForJobTitleSkills";
import GoBack from "@/app/components/GoBack";
import DeleteItemButton from "@/app/components/DeleteItemButton";
import EditItemButton from "@/app/components/EditItemButton";
import isUserAllowed from "@/app/utils/isUserAllowed";
import currentUser from "@/app/utils/currentUser";

const ArticlePage = async (props: { params: Promise<{ id: string }> }) => {
	// await new Promise((resolve) => setTimeout(resolve, 2000));
	const params = await props.params;
	const id = params.id;
	const article = await fetchInterceptor(
		`${process.env.NEXT_PUBLIC_APIBASE}/articles/${id}`
	);
	const author = await fetchInterceptor(
		`${process.env.NEXT_PUBLIC_APIBASE}/users/${article.userId}`
	);

	return (
		<Container my={{ initial: "0", md: "5" }} p={{ initial: "4", md: "0" }}>
			<Flex justify="end" mb="3">
				<GoBack />
			</Flex>
			<Grid columns={{ initial: "1", md: "3" }} mt="6" gap="5">
				<Box className="col-span-2" mr="3">
					<Suspense>
						<AspectRatio ratio={9 / 3}>
							<img
								src={`data:image/jpeg;base64, ${article.cover}`}
								style={{
									objectFit: "cover",
									width: "100%",
									height: "100%",
									borderRadius: "5px",
								}}
							/>
						</AspectRatio>
					</Suspense>
					<Flex my="5" direction="column" gap="5">
						<Flex
							justify="between"
							direction={{ initial: "column", md: "row" }}
							gap={{ initial: "3", md: "0" }}
						>
							<Flex>
								<PinArticleButton articleId={article.id} />
								<Heading>{article.title}</Heading>
							</Flex>
							{(await isUserAllowed(currentUser, "Editor")) && (
								<Flex gap="3" direction={{ initial: "column", md: "row" }}>
									<EditItemButton kind={"article"} id={article.id} />
									<DeleteItemButton kind={"article"} id={article.id} />
								</Flex>
							)}
						</Flex>
						<Text as="p">{article.description}</Text>
					</Flex>
					<Flex gap="3" direction="column">
						{article.internalUseOnly && (
							<Flex direction="column">
								<Separator my="3" size="4" />
								<Flex>
									<Badge color="orange" mr="2">
										Warning
									</Badge>
									<Text>This article is for internal use only</Text>
								</Flex>
							</Flex>
						)}
						{article.aiGenerated && (
							<Flex direction="column">
								<Flex>
									<Badge color="green" mr="2">
										AI
									</Badge>
									<Text>This article was generated by AI</Text>
								</Flex>
							</Flex>
						)}
					</Flex>
					<Separator my="4" size="4" />
					{/* <Flex>
						<ArticleRelevanceForJobTitleSkills article={article} />
					</Flex> */}
				</Box>
				<Box>
					<Card className="shadow-lg">
						<Box p="3">
							<Flex justify={"between"}>
								<Heading size="2">Article uploaded by: </Heading>
								<Text>{`${author.firstName} ${author.lastName}`}</Text>
							</Flex>

							<Separator my="3" size="4" />
							<Flex justify={"between"}>
								<Heading size="2">Duration</Heading>
								<Text>{article.duration} pages</Text>
							</Flex>

							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Media</Heading>
								<Text>{article.media.name}</Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Source</Heading>
								<Text>{article.source.name}</Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Educational Framework</Heading>
								<Text>{article.educationalFramework.name}</Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Educational Methodology</Heading>
								<Text>{article.educationalMethodology.name}</Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between">
								<Heading size="2">Educational Tool</Heading>
								<Text>{article.educationalTool.name}</Text>
							</Flex>
							<Separator my="3" size="4" />
							<Flex justify="between" direction={"column"} gap="2">
								<Heading size="2">
									Valid for the following Business units
								</Heading>
								{typeof (
									article.articleBusinessUnits.lenght === "undefined"
								) ? (
									<Text size="2">
										This article is suitable for all business units
									</Text>
								) : (
									<ul>
										{article.articleBusinessUnits.map((bu, index) => (
											<li>{bu.name}</li>
										))}
									</ul>
								)}
							</Flex>
							<Flex justify="between" direction={"column"} gap="2">
								<Separator my="3" size="4" />
								<Heading size="2">Valid for the following Regions</Heading>
								{typeof (article.articleRegions.lenght === "undefined") ? (
									<Text size="2">This article is suitable for all regions</Text>
								) : (
									<ul>
										{article.articleRegions.map((r, index) => (
											<li>{r.name}</li>
										))}
									</ul>
								)}
							</Flex>
							{typeof (article.articleCourses.lenght === "undefined") ? (
								<div></div>
							) : (
								<Flex justify="between" direction={"column"} gap="2">
									<Heading size="2">Courses</Heading>
									<ul>
										{article.articleCourses.map((c, index) => (
											<li>{c.name}</li>
										))}
									</ul>
								</Flex>
							)}

							<Flex minWidth={"100%"} mt="5">
								<DownloadFile articleId={article.id} />
							</Flex>
						</Box>
					</Card>
				</Box>
			</Grid>
		</Container>
	);
};

export default ArticlePage;
